name: jira-lint
on: [pull_request]

jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - name: print-vars
        run: echo ${{ env.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{secrets.IH_JIRA_API_SECRET_YM}}
      - uses: invitation-homes/jira-lint@v1
        name: jira-lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.IH_JIRA_API_SECRET_YM }}
          jira-base-url: https://invitationhomes.atlassian.net
          skip-comments: true
          pr-threshold: 1000