name: pylint_validation
on: pull_request

jobs:  
  pythonFiles: # Job that list python files
    runs-on: ubuntu-latest
    outputs:
      pyfiles: ${{ steps.set-py-files.outputs.pyfiles }} # generate output name python files by using inner step output
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Get main branch
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
      
      - name: Set pythonFiles
        id: set-py-files # Give it an id to handle to get step outputs in the outputs key above
        run: echo "::set-output name=pyfiles::$(git diff --name-only --diff-filter=ACMRT HEAD origin/${{ github.event.pull_request.base.ref }} -- '*.py' | uniq | jq -R -s -c 'split("\n")[:-1]' | jq -r '.[] | ("./" + .)' | jq -R -s -c 'split("\n")[:-1] | join(",")')"
        # Define step output named dir base on ls command transformed to JSON thanks to jq
      - name: echo data
        run: echo ${{steps.set-py-files.outputs.pyfiles}}
      - name: echo data
        run: echo ${{ github.repository == 'octo-org/octo-repo-prod' }}
  flake8_py3:
    runs-on: ubuntu-latest
    needs: pythonFiles
    if: ${{ needs.pythonFiles.outputs.pyfiles == 'octo-org/octo-repo-prod' }}
    steps:
      - name: Echo files to scan
        run: echo ${{ needs.pythonFiles.outputs.pyfiles }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          architecture: x64
 
      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: python3.8 -m flake8 --filename=${{ needs.pythonFiles.outputs.pyfiles }}