name: pylint_validation
on: pull_request

jobs:  
  pythonFiles: # Job that list python files
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name python files by using inner step output
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Get main branch
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
  
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          architecture: x64
 
      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: python3.8 -m flake8 --filename=./test.py,./test2.py